language: go

go: "1.12"
git:
  depth: 1
install: true
notifications:
  email: false
script: 
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)