sudo: false
language: go
go: "1.x"
git:
  depth: 1
install: true
notifications:
  email: false
before_install:
  - go get -u github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
after_success: coveralls